vscode:
  extensions:
    - golang.go
    - premparihar.gotestexplorer
    - earthly.earthfile-syntax-highlighting

tasks:
  - init: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
    name: earthly
  - init: go get -v -t -d ./...

ports:
  - port: 8080
    visibility: private
    onOpen: ignore
