run:
  issues-exit-code: 1
  tests: true
  timeout: 5m
  skip-dirs:
    - gen
    - mocks
    - vendor

linters:
  disable-all: true
  enable:
    - golint
    - gosec
    - gocyclo
    - whitespace
    - misspell
    - goimports
    - revive
    - gofmt

issues:
  exclude-rules:
    # helpers in tests often (rightfully) pass a *testing.T as their first argument
    - path: _test\.go
      text: "context.Context should be the first parameter of a function"
      linters:
        - revive
    # Yes, they are, but it's okay in a test
    - path: _test\.go
      text: "exported func.*returns unexported type.*which can be annoying to use"
      linters:
        - revive

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - cancelled
  goimports:
    local-prefixes: github.com/superflat
