// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: parti/v1/fsm.proto

package partiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsmPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string     `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key   string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value *anypb.Any `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FsmPutRequest) Reset() {
	*x = FsmPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmPutRequest) ProtoMessage() {}

func (x *FsmPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmPutRequest.ProtoReflect.Descriptor instead.
func (*FsmPutRequest) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{0}
}

func (x *FsmPutRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FsmPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FsmPutRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type FsmGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *FsmGetRequest) Reset() {
	*x = FsmGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmGetRequest) ProtoMessage() {}

func (x *FsmGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmGetRequest.ProtoReflect.Descriptor instead.
func (*FsmGetRequest) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{1}
}

func (x *FsmGetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FsmGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FsmRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *FsmRemoveRequest) Reset() {
	*x = FsmRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmRemoveRequest) ProtoMessage() {}

func (x *FsmRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmRemoveRequest.ProtoReflect.Descriptor instead.
func (*FsmRemoveRequest) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{2}
}

func (x *FsmRemoveRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FsmRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FsmGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]*anypb.Any `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FsmGroup) Reset() {
	*x = FsmGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmGroup) ProtoMessage() {}

func (x *FsmGroup) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmGroup.ProtoReflect.Descriptor instead.
func (*FsmGroup) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{3}
}

func (x *FsmGroup) GetData() map[string]*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type FsmGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups map[string]*FsmGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FsmGroups) Reset() {
	*x = FsmGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmGroups) ProtoMessage() {}

func (x *FsmGroups) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmGroups.ProtoReflect.Descriptor instead.
func (*FsmGroups) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{4}
}

func (x *FsmGroups) GetGroups() map[string]*FsmGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type BulkFsmPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*FsmPutRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *BulkFsmPutRequest) Reset() {
	*x = BulkFsmPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_fsm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkFsmPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFsmPutRequest) ProtoMessage() {}

func (x *BulkFsmPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_fsm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFsmPutRequest.ProtoReflect.Descriptor instead.
func (*BulkFsmPutRequest) Descriptor() ([]byte, []int) {
	return file_parti_v1_fsm_proto_rawDescGZIP(), []int{5}
}

func (x *BulkFsmPutRequest) GetRequests() []*FsmPutRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_parti_v1_fsm_proto protoreflect.FileDescriptor

var file_parti_v1_fsm_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x73, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x46, 0x73, 0x6d,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37,
	0x0a, 0x0d, 0x46, 0x73, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3a, 0x0a, 0x10, 0x46, 0x73, 0x6d, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x08, 0x46, 0x73, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x73, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x4d, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x46, 0x73, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x37, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x73, 0x6d, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x1a, 0x4d, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x73, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x48, 0x0a, 0x11, 0x42, 0x75, 0x6c, 0x6b, 0x46,
	0x73, 0x6d, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x73, 0x6d, 0x50, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x42, 0x78, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76,
	0x31, 0x42, 0x08, 0x46, 0x73, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a,
	0x1b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50,
	0x58, 0x58, 0xaa, 0x02, 0x08, 0x50, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_parti_v1_fsm_proto_rawDescOnce sync.Once
	file_parti_v1_fsm_proto_rawDescData = file_parti_v1_fsm_proto_rawDesc
)

func file_parti_v1_fsm_proto_rawDescGZIP() []byte {
	file_parti_v1_fsm_proto_rawDescOnce.Do(func() {
		file_parti_v1_fsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_parti_v1_fsm_proto_rawDescData)
	})
	return file_parti_v1_fsm_proto_rawDescData
}

var file_parti_v1_fsm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_parti_v1_fsm_proto_goTypes = []interface{}{
	(*FsmPutRequest)(nil),     // 0: parti.v1.FsmPutRequest
	(*FsmGetRequest)(nil),     // 1: parti.v1.FsmGetRequest
	(*FsmRemoveRequest)(nil),  // 2: parti.v1.FsmRemoveRequest
	(*FsmGroup)(nil),          // 3: parti.v1.FsmGroup
	(*FsmGroups)(nil),         // 4: parti.v1.FsmGroups
	(*BulkFsmPutRequest)(nil), // 5: parti.v1.BulkFsmPutRequest
	nil,                       // 6: parti.v1.FsmGroup.DataEntry
	nil,                       // 7: parti.v1.FsmGroups.GroupsEntry
	(*anypb.Any)(nil),         // 8: google.protobuf.Any
}
var file_parti_v1_fsm_proto_depIdxs = []int32{
	8, // 0: parti.v1.FsmPutRequest.value:type_name -> google.protobuf.Any
	6, // 1: parti.v1.FsmGroup.data:type_name -> parti.v1.FsmGroup.DataEntry
	7, // 2: parti.v1.FsmGroups.groups:type_name -> parti.v1.FsmGroups.GroupsEntry
	0, // 3: parti.v1.BulkFsmPutRequest.requests:type_name -> parti.v1.FsmPutRequest
	8, // 4: parti.v1.FsmGroup.DataEntry.value:type_name -> google.protobuf.Any
	3, // 5: parti.v1.FsmGroups.GroupsEntry.value:type_name -> parti.v1.FsmGroup
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_parti_v1_fsm_proto_init() }
func file_parti_v1_fsm_proto_init() {
	if File_parti_v1_fsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parti_v1_fsm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parti_v1_fsm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parti_v1_fsm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parti_v1_fsm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parti_v1_fsm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parti_v1_fsm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkFsmPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parti_v1_fsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parti_v1_fsm_proto_goTypes,
		DependencyIndexes: file_parti_v1_fsm_proto_depIdxs,
		MessageInfos:      file_parti_v1_fsm_proto_msgTypes,
	}.Build()
	File_parti_v1_fsm_proto = out.File
	file_parti_v1_fsm_proto_rawDesc = nil
	file_parti_v1_fsm_proto_goTypes = nil
	file_parti_v1_fsm_proto_depIdxs = nil
}
