// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: parti/v1/state.proto

package partiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionOwnership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Owner       string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	IsPaused    bool   `protobuf:"varint,3,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
}

func (x *PartitionOwnership) Reset() {
	*x = PartitionOwnership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parti_v1_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartitionOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionOwnership) ProtoMessage() {}

func (x *PartitionOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_parti_v1_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionOwnership.ProtoReflect.Descriptor instead.
func (*PartitionOwnership) Descriptor() ([]byte, []int) {
	return file_parti_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionOwnership) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionOwnership) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PartitionOwnership) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

var File_parti_v1_state_proto protoreflect.FileDescriptor

var file_parti_v1_state_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31,
	0x22, 0x6a, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x42, 0x7a, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x1b, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa,
	0x02, 0x08, 0x50, 0x61, 0x72, 0x74, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x50, 0x61, 0x72, 0x74, 0x69, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parti_v1_state_proto_rawDescOnce sync.Once
	file_parti_v1_state_proto_rawDescData = file_parti_v1_state_proto_rawDesc
)

func file_parti_v1_state_proto_rawDescGZIP() []byte {
	file_parti_v1_state_proto_rawDescOnce.Do(func() {
		file_parti_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_parti_v1_state_proto_rawDescData)
	})
	return file_parti_v1_state_proto_rawDescData
}

var file_parti_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parti_v1_state_proto_goTypes = []interface{}{
	(*PartitionOwnership)(nil), // 0: parti.v1.PartitionOwnership
}
var file_parti_v1_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parti_v1_state_proto_init() }
func file_parti_v1_state_proto_init() {
	if File_parti_v1_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parti_v1_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartitionOwnership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parti_v1_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parti_v1_state_proto_goTypes,
		DependencyIndexes: file_parti_v1_state_proto_depIdxs,
		MessageInfos:      file_parti_v1_state_proto_msgTypes,
	}.Build()
	File_parti_v1_state_proto = out.File
	file_parti_v1_state_proto_rawDesc = nil
	file_parti_v1_state_proto_goTypes = nil
	file_parti_v1_state_proto_depIdxs = nil
}
