name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.15
      - name: Earthly version
        run: earthly --version
      - name: Linter
        run: |
          earthly --no-cache +lint

